import Link from "next/link";
import { ArrowLeft, BarChart3, CircleDollarSign, FlaskConical } from "lucide-react";
import { BrandLink } from "@/src/components/marketing/Brand";

const termsItems = [
  {
    icon: FlaskConical,
    title: "Development sandbox",
    body: "This application is a sandbox trading interface for development and testing. It does not execute real trades or manage real collateral.",
  },
  {
    icon: BarChart3,
    title: "Simulated exchange state",
    body: "All balances, orders, market data, and positions shown in the app are simulated or locally generated by the connected backend services.",
  },
  {
    icon: CircleDollarSign,
    title: "No production funds",
    body: "Use this environment only for testing the local exchange workflow. Do not treat demo balances, PnL, or fills as financial records.",
  },
];

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#07090d] px-4 text-[#f7fbff]">
      <header className="mx-auto flex h-20 w-full max-w-5xl items-center justify-between border-b border-white/10">
        <BrandLink />
        <Link href="/signin" className="flex items-center gap-2 rounded-md px-3 py-2 text-sm font-semibold text-[#aab4c0] transition hover:bg-white/[0.05] hover:text-white">
          <ArrowLeft className="h-4 w-4" />
          Sign in
        </Link>
      </header>

      <main className="mx-auto w-full max-w-3xl py-14">
        <div className="mb-10">
          <div className="mb-3 text-sm font-semibold text-lime">Terms</div>
          <h1 className="text-4xl font-bold text-white">Sandbox usage terms.</h1>
          <p className="mt-4 text-sm leading-7 text-[#aab4c0]">
            These terms clarify that Backpack Futures in this repo is a local demo exchange workflow.
          </p>
        </div>

        <div className="space-y-4">
          {termsItems.map(({ icon: Icon, title, body }) => (
            <section key={title} className="rounded-lg border border-white/10 bg-[#0c121b] p-5">
              <div className="mb-3 flex items-center gap-3">
                <div className="flex h-9 w-9 items-center justify-center rounded-md bg-lime/[0.08] text-lime">
                  <Icon className="h-4 w-4" />
                </div>
                <h2 className="text-lg font-bold text-white">{title}</h2>
              </div>
              <p className="text-sm leading-7 text-[#aab4c0]">{body}</p>
            </section>
          ))}
        </div>
      </main>
    </div>
  );
}
