import Link from "next/link";
import { ArrowLeft, Wallet } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#0b0e11] text-white flex flex-col items-center px-4">
      <header className="w-full max-w-5xl h-20 flex items-center justify-between border-b border-[#24303f]/40">
        <Link href="/" className="flex items-center gap-2">
          <div className="w-9 h-9 rounded-xl bg-[#e9fc50] flex items-center justify-center">
            <Wallet className="w-5 h-5 text-[#0b0e11]" />
          </div>
          <span className="text-xl font-bold tracking-tight">
            BACKPACK<span className="text-[#e9fc50] font-extrabold font-mono ml-0.5">FUTURES</span>
          </span>
        </Link>
        <Link href="/signin" className="text-xs text-[#848e9c] hover:text-white flex items-center gap-1">
          <ArrowLeft className="w-3.5 h-3.5" />
          Sign in
        </Link>
      </header>

      <main className="w-full max-w-3xl py-14">
        <h1 className="text-3xl font-bold tracking-tight mb-4">Terms</h1>
        <div className="space-y-5 text-sm leading-7 text-[#c7d0dc]">
          <p>
            This application is a sandbox trading interface for development and testing. It does not execute real trades or manage real collateral.
          </p>
          <p>
            All balances, orders, market data, and positions shown in the app are simulated or locally generated by the connected backend services.
          </p>
          <p>
            Use this environment only for testing the local exchange workflow.
          </p>
        </div>
      </main>
    </div>
  );
}
