FROM oven/bun:1.3.14-slim AS base
WORKDIR /repo
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential python3 postgresql-client \
    && rm -rf /var/lib/apt/lists/*

COPY package.json bun.lock ./
COPY apps ./apps
COPY packages ./packages

RUN bun install --frozen-lockfile
RUN cd packages/db && bunx prisma generate
ARG APP_DIR
WORKDIR /repo/${APP_DIR}
CMD ["bun" , "run" , "index.ts"]    